free_thresh: 0.196
image: /images/amsterdam_cropped_.png
map_bottom: 8027.0
map_left: 7412.0
map_right: 8598.0
map_top: 7427.0
negate: 0
occupied_thresh: 0.65
origin: [629869.0, 5800276.0, 0.0]
resolution: 0.5
