free_thresh: 0.196
image: /images/amsterdam_cropped_test.png
map_bottom: 3215.0
map_left: 4241.0
map_right: 4369.0
map_top: 3087.0
negate: 0
occupied_thresh: 0.65
origin: [626698.0, 5807588.0, 0.0]
resolution: 0.5
